pipeline {
    agent {
     node {
    		label 'myawsvm'
    		}
    }

    stages {
        stage('AppCode-Checkout') {
            steps {
                git changelog: false, poll: false, url: 'https://github.com/awsdevopspractise/aws-b4-maven-app.git'
            }
            }
        stage('App-Build') {
            steps {
                sh 'mvn clean package'
            }
            }
        stage('Docker Build & Push') {
            steps {

            script {

            withCredentials([string(credentialsId: 'docker-token', variable: 'token')]) {

    			sh 'docker login -u pylifedevops -p ${token}'
			}

            }   
                sh 'docker build . -t pylifedevops/cicd:v2'
                sh 'docker push pylifedevops/cicd:v2'
            }                        
        }
    }
}